routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Policies\PermissionController;
use App\Http\Controllers\Policies\RoleActionController;
use App\Http\Controllers\Policies\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';

Route::prefix('/dashboard')->group(function () {
    Route::get('/profile', ProfileController::class)->middleware('auth')->name('profile');

    Route::post('/user/assign-role', [RoleActionController::class, 'addRole'])->name('assign-role');
    Route::resource('/users', UserController::class)->middleware(['auth']);

    Route::resource('/policies/role', RoleController::class)->middleware(['auth']);
    Route::resource('/policies/permissions', PermissionController::class)->middleware(['auth']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasPermissions;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public static function search($search)
    {
        return empty($search) ? static::query()
            : static::where('id', 'like', '%' . $search . '%')
            ->orWhere('name', 'like', '%' . $search . '%')
            ->orWhere('email', 'like', '%' . $search . '%');
    }
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Repository\UserRepositoryInterface;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * userRepository
     *
     * @var mixed
     */
    private $userRepository;
    /**
     * __construct
     *
     * @param  mixed $userRepository
     * @return void
     */
    public function __construct(UserRepositoryInterface $userRepository)
    {
        $this->userRepository = $userRepository;
    }
    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return response()->json($this->userRepository->all(['id', 'name', 'email'], array('roles')), 200);
    }
    /**
     * find
     *
     * @param  mixed $id
     * @return void
     */
    public function find($id)
    {
        return response()->json($this->userRepository->findById($id, ['id', 'name', 'email'], array('roles'), []), 200);
    }
}

app/Http/Controllers/Users/UserController.php
<?php

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use RealRashid\SweetAlert\Facades\Alert;

class UserController extends Controller
{
    public $search = '';
    public $perPage = 10;
    public $sortField = 'id';
    public $sortAsc = true;

    /**
     * __construct to Avoid User whit out role Acces this controller via URL
     *
     * @return void
     */
    // public function __construct()
    // {
    //     $this->middleware(['role:admin']);
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::count();
        return view('pages.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required | min:5',
            'email' => 'required | email|unique:users',
            'password' => 'required | | min:5',
        ]);

        $user               = new User;
        $user->name         = $request->name;
        $user->email        = $request->email;
        $user->password     = Hash::make($request->password);
        $user->save();
        Alert::success('Success', 'Successfully Create new User');
        return redirect(url('dashboard/users'))->with('success', 'A new User Has Been Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::with('roles')->get();
        $role = Role::with('permissions')->get();
        $AvailableRole = Role::all();
        // return response()->json([$user->find($id), $role->find($id)]);
        return view('pages.users.show', ['user' => $user->find($id), 'role' => $role->find($id), 'AvailableRole' => $AvailableRole]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/users/create.blade.php
<x-app-layout>
    <div class="w-4/5 min-h-screen boder-l-2 bg-gray-100">
        <div class="p-5">
            <form action="{{route('users.store')}}" method="post">
                @csrf
                <!-- This example requires Tailwind CSS v2.0+ -->
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 sm:px-6">
                        <h3 class="text-lg leading-6 font-medium text-gray-900">
                        {{__('Create a New User')}}
                        </h3>
                        <p class="mt-1 max-w-2xl text-sm text-gray-500">
                    {{__('Please fill in all fields with valid data')}}
                        </p>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            Name
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <x-input id="name" class="block mt-1 w-full {{ $errors->has('email') ? 'border-red-500' :'' }}" type="text" name="name" :value="old('name')" placeholder="{{__('Enter Name')}}" autofocus />
                                @error('name')
                                    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                        {{$message}}
                                    </span>
                                @enderror
                            </dd>
                        </div>
                        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            Email
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <x-input id="email" class="block mt-1 w-full {{ $errors->has('email') ? 'border-red-500' :'' }}" type="text" name="email" :value="old('email')" placeholder="{{__('Enter E-mail')}}" autofocus />
                                @error('email')
                                    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                        {{$message}}
                                    </span>
                                @enderror
                            </dd>
                        </div>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            Password
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <x-input id="password" class="block mt-1 w-full {{ $errors->has('password') ? 'border-red-500' :'' }}" type="password" name="password" :value="old('password')" placeholder="{{__('Enter a Password')}}" autofocus />
                                @error('password')
                                    <span class="flex items-center font-medium tracking-wide text-red-500 text-xs mt-1 ml-1">
                                        {{$message}}
                                    </span>
                                @enderror
                            </dd>
                        </div>
                        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            Salary expectation
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            $120,000
                            </dd>
                        </div>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            About
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            Fugiat ipsum ipsum deserunt culpa aute sint do nostrud anim incididunt cillum culpa consequat. Excepteur qui ipsum aliquip consequat sint. Sit id mollit nulla mollit nostrud in ea officia proident. Irure nostrud pariatur mollit ad adipisicing reprehenderit deserunt qui eu.
                            </dd>
                        </div>
                        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">
                            Attachments
                            </dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                                <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                <div class="w-0 flex-1 flex items-center">
                                    <!-- Heroicon name: paper-clip -->
                                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="ml-2 flex-1 w-0 truncate">
                                    resume_back_end_developer.pdf
                                    </span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                    </a>
                                </div>
                                </li>
                                <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                <div class="w-0 flex-1 flex items-center">
                                    <!-- Heroicon name: paper-clip -->
                                    <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                    </svg>
                                    <span class="ml-2 flex-1 w-0 truncate">
                                    coverletter_back_end_developer.pdf
                                    </span>
                                </div>
                                <div class="ml-4 flex-shrink-0">
                                    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
                                    Download
                                    </a>
                                </div>
                                </li>
                            </ul>
                            </dd>
                        </div>
                        </dl>
                    </div>
                </div>
                <div class="flex flex-row justify-end items-center py-5 gap-x-3">
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-full text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</button>
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-full text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Create & Add Another</button>
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-full text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Create</button>
                </div>
            </form>
        </div>
        {{-- Footer --}}
        <div class="flex justify-between p-5">
            <div class="text-sm text-gray-500 font-bold">
                <a href="#">Privacy</a>
                <a href="#">Policy</a>
            </div>
            <div class="text-sm text-gray-500 font-bold">@ 2020 Workflow, All Right Reserved</div>
        </div>
    </div>
</x-app-layout>

resources/views/pages/users/index.blade.php
<x-app-layout>
    <div class="w-4/5 min-h-screen boder-l-2 bg-gray-100">
        {{-- Header --}}
        <div class="flex items-center justify-between border-b shadow-sm px-5 py-2 bg-white">
            <div>
                <h1 class="text-lg">User List</h1>
            </div>
            <div class="flex gap-x-2">
                <a href="{{route('users.create')}}" class="inline-flex items-center px-4 py-2 rounded-lg bg-green-600 text-sm font-medium text-white hover:text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-green-100 focus:ring-green-500"><span class="font-bold text-sm">Create New User</span></a>
            </div>
        </div>
        {{-- Alert Here --}}
        @include('components.alert')
        {{-- Table Content--}}
        <div class="px-5">
            @livewire('datatable')
        </div>
        {{-- Footer --}}
        <div class="flex justify-between p-5">
            <div class="text-sm text-gray-500 font-bold">
                <a href="#">Privacy</a>
                <a href="#">Policy</a>
            </div>
            <div class="text-sm text-gray-500 font-bold">@ 2020 Workflow, All Right Reserved</div>
        </div>
    </div>
</x-app-layout>

resources/views/pages/users/show.blade.php
<x-app-layout>
    <div class="w-4/5 min-h-screen boder-l-2 bg-gray-100">
        <div class="p-5">
        <form action="{{route('assign-role')}}" method="POST">
            @csrf
            <!-- This example requires Tailwind CSS v2.0+ -->
            <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="px-4 py-5 sm:px-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900">
                <span class="font-bold text-green-500">Users Information</span>
                </h3>
                <p class="mt-1 max-w-2xl text-sm text-gray-500">
                Personal details of this user.
                <input type="hidden" name="id" value="{{$user->id}}">
                </p>
            </div>
            <div class="border-t border-gray-200">
                <dl>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Full name</span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{$user->name}}
                    </dd>
                </div>
                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Role User</span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        @forelse ($user->roles as $roles)
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                {{ $roles->name }}
                            </span>
                            @empty 
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">No Attached Role</span>
                        @endforelse
                    </dd>
                </div>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Email address</span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{$user->email}}
                    </dd>
                </div>
                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Date Registered</span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">                        
                        This user was registered at 
                            <span class="font-bold text-green-700 px-2 bg-green-200 rounded-full">{{$user->created_at->format('H:i:s')}}</span>
                            on
                            <span class="font-bold text-green-700 px-2 bg-green-200 rounded-full">{{$user->created_at->format('d-M-Y')}}</span>
                            <span class="font-bold text-green-700 px-2">{{$user->created_at->diffForHumans()}}</span>
                    </dd>
                </div>
                <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Latest Updated</span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        This user was registered at 
                            <span class="font-bold text-green-700 px-2 bg-green-200 rounded-full">{{$user->updated_at->format('H:i:s')}}</span>
                            on
                            <span class="font-bold text-green-700 px-2 bg-green-200 rounded-full">{{$user->updated_at->format('d-M-Y')}}</span>
                            <span class="font-bold text-green-700 px-2">{{$user->updated_at->diffForHumans()}}</span>
                    </dd>
                </div>
                <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">
                    <span class="font-bold text-green-500">Permissions Scope of
                    @foreach ($user->roles as $role)
                        {{$role->name}}
                    @endforeach is </span>
                    </dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                        <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
                            {{-- Check when this user have a role/no --}}
                            @forelse ($user->roles as $role)
                            {{-- Since this User have a role, lets cek that corresponding role have any permission/no  --}}
                                @forelse ($role->permissions as $permission)    
                                    <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
                                        <div class="w-0 flex-1 flex items-center">
                                            <!-- Heroicon name: paper-clip -->
                                            <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                                            </svg>
                                            <span class="ml-2 flex-1 w-0 truncate">
                                            {{$permission->name}}
                                            </span>
                                        </div>
                                        <div class="ml-4 flex-shrink-0">
                                            <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
                                            {{'See Detail'}}
                                            </a>
                                        </div>
                                    </li>
                                    @empty
                                    <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm bg-yellow-100">
                                        <span class="ml-2 flex-1 w-0 truncate text-yellow-500 font-bold">
                                            {{'This User is Granted  to all Permissions'}}
                                        </span>
                                    </li>
                                @endforelse
                            @empty
                            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm bg-red-100">
                                <span class="ml-2 flex-1 w-0 truncate text-red-500 font-bold">
                                    {{ 'This User do not Have Any Role and permissions attachments' }}
                                </span>
                            </li>
                            @endforelse
                        </ul>
                    </dd>
                </div>
                </dl>
            </div>
            </div>
        </div>

        {{-- SHOW SINCE THIS USER DONT HAVE A ROLE --}}
        @forelse ($user->roles as $role)
            
        @empty
            <div class="p-5">
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 sm:px-6">
                        <h3 class="text-lg leading-6 font-medium text-gray-900">
                        <span class="font-bold Text-lg text-green-500">Assign Role For This User</span> 
                        </h3>
                        <p class="mt-1 max-w-2xl text-sm text-gray-500">
                        Because this user don't have any role attached, you can attach role for this user
                        </p>
                    </div>
                    <div class="border-t border-gray-200">
                        <dl>
                            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                                <dt class="text-sm font-medium text-gray-500">
                                Select Available Role
                                </dt>
                                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <x-label for="sort" :value="__('Please Select Role')" />
                                <select class="block mt-1 w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50'" name="name" id="name">
                                    <option value="">Select Role</option>
                                    @foreach ($AvailableRole as $Collection)
                                        <option value="{{$Collection->name}}">{{$Collection->name}}</option>
                                    @endforeach
                                </select>
                                </dd>
                            </div>
                        </dl>
                    </div>
                </div>
                <div class="flex flex-row justify-end items-center py-5 gap-x-3">
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-bold rounded-lg text-white bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Cancel</button>
                    <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-bold rounded-lg text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Add</button>
                </div>
            </div>
        @endforelse
        {{-- END SECTION --}}
        </form>

        {{-- Footer --}}
        <div class="flex justify-between p-5">
            <div class="text-sm text-gray-500 font-bold">
                <a href="#">Privacy</a>
                <a href="#">Policy</a>
            </div>
            <div class="text-sm text-gray-500 font-bold">@ 2020 Workflow, All Right Reserved</div>
        </div>
    </div>
</x-app-layout>